"""empty message

Revision ID: 291a49bb420e
Revises: 
Create Date: 2021-10-17 00:18:44.838081

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '291a49bb420e'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('complaints', sa.Column('amount', sa.Float(), nullable=False))
    op.add_column('complaints', sa.Column('status', sa.Enum('pending', 'approved', 'rejected', name='state'), nullable=False))
    op.drop_column('complaints', 'role')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('complaints', sa.Column('role', postgresql.ENUM('pending', 'approved', 'rejected', name='state'), autoincrement=False, nullable=False))
    op.drop_column('complaints', 'status')
    op.drop_column('complaints', 'amount')
    # ### end Alembic commands ###
