"""Unecessary column

Revision ID: 0a19c7fa701b
Revises: b9171c549964
Create Date: 2021-09-28 20:41:30.927394

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0a19c7fa701b'
down_revision = 'b9171c549964'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('books', sa.Column('some_column', sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('books', 'some_column')
    # ### end Alembic commands ###
