"""Create a releationship and readers table"

Revision ID: 93273c8c1e15
Revises: 0a19c7fa701b
Create Date: 2021-09-28 21:01:09.676365

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '93273c8c1e15'
down_revision = '0a19c7fa701b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('books', sa.Column('reader_pk', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'books', 'readers', ['reader_pk'], ['pk'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'books', type_='foreignkey')
    op.drop_column('books', 'reader_pk')
    # ### end Alembic commands ###
